version: '3'

services:
  server:
    build:
      context: ./cours-api-rest-api-front
    ports:
      - "3000:3000"
    env_file:
      - ./cours-api-rest-api-front/.env
    environment:
      MONGO_URL: mongodb://mongo:27017/coursapirest
    depends_on:
      - mongo
    networks:
      - api-network
    volumes:
      - server-data:/app/server/data

  back:
    build:
      context: ./cours-api-rest-back
    ports:
      - "8080:80"
    env_file:
      - ./cours-api-rest-back/.env
    depends_on:
      - mongo
    networks:
      - api-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  
  mongo:
    image: mongo:bionic
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: coursapirest
    networks:
      - api-network
    volumes:
      - mongo-data:/data/db

networks:
  api-network:
    driver: bridge

volumes:
  server-data:
  backoffice-data:
  mongo-data: